Change WRITE_GITHUB_PACKAGES_USERNAME to a variable
Signed-off-by: Jade Carino <carino_jade@yahoo.co.uk>

diff --git a/.github/workflows/check-required-secrets-configured.yaml b/.github/workflows/check-required-secrets-configured.yaml
--- a/.github/workflows/check-required-secrets-configured.yaml
+++ b/.github/workflows/check-required-secrets-configured.yaml
@@ -89,9 +89,10 @@ jobs:
         if: ${{ inputs.check_write_github_packages_username == 'true' }}
         continue-on-error: true
         env:
-          WRITE_GITHUB_PACKAGES_USERNAME: ${{ secrets.WRITE_GITHUB_PACKAGES_USERNAME }}
+          WRITE_GITHUB_PACKAGES_USERNAME: $WRITE_GITHUB_PACKAGES_USERNAME
         run: |
           if [ -z "${WRITE_GITHUB_PACKAGES_USERNAME}" ] || [ "${WRITE_GITHUB_PACKAGES_USERNAME}" = "" ]; then
+            echo "WRITE_GITHUB_PACKAGES_USERNAME is not set. Please see the output of the 'Report missing repository secrets/variables' job below."
             exit 1
           else
             echo "WRITE_GITHUB_PACKAGES_USERNAME is set."
@@ -105,6 +106,7 @@ jobs:
           WRITE_GITHUB_PACKAGES_TOKEN: ${{ secrets.WRITE_GITHUB_PACKAGES_TOKEN }}
         run: |
           if [ -z "${WRITE_GITHUB_PACKAGES_TOKEN}" ] || [ "${WRITE_GITHUB_PACKAGES_TOKEN}" = "" ]; then
+            echo "WRITE_GITHUB_PACKAGES_TOKEN is not set. Please see the output of the 'Report missing repository secrets/variables' job below."
             exit 1
           else
             echo "WRITE_GITHUB_PACKAGES_TOKEN is set."
@@ -118,6 +120,7 @@ jobs:
           READ_GITHUB_PACKAGES_USERNAME: ${{ secrets.READ_GITHUB_PACKAGES_USERNAME }}
         run: |
           if [ -z "${READ_GITHUB_PACKAGES_USERNAME}" ] || [ "${READ_GITHUB_PACKAGES_USERNAME}" = "" ]; then
+            echo "READ_GITHUB_PACKAGES_USERNAME is not set. Please see the output of the 'Report missing repository secrets/variables' job below."
             exit 1
           else
             echo "READ_GITHUB_PACKAGES_USERNAME is set."
@@ -131,24 +134,12 @@ jobs:
           READ_GITHUB_PACKAGES_TOKEN: ${{ secrets.READ_GITHUB_PACKAGES_TOKEN }}
         run: |
           if [ -z "${READ_GITHUB_PACKAGES_TOKEN}" ] || [ "${READ_GITHUB_PACKAGES_TOKEN}" = "" ]; then
+            echo "READ_GITHUB_PACKAGES_TOKEN is not set. Please see the output of the 'Report missing repository secrets/variables' job below."
             exit 1
           else
             echo "READ_GITHUB_PACKAGES_TOKEN is set."
           fi
         id: check-read-github-packages-token
-
-      - name: Check if MAVEN_SETTINGS_XML is configured in this repository
-        if: ${{ inputs.check_maven_settings_xml == 'true' }}
-        continue-on-error: true
-        env:
-          MAVEN_SETTINGS_XML: ${{ secrets.MAVEN_SETTINGS_XML }}
-        run: |
-          if [ -z "${MAVEN_SETTINGS_XML}" ] || [ "${MAVEN_SETTINGS_XML}" == "" ]; then
-            exit 1
-          else
-            echo "MAVEN_SETTINGS_XML is set."
-          fi
-        id: check-maven-settings-xml
 
       - name: Check if GPG_KEY is set in this repository
         if: ${{ inputs.check_gpg_key == 'true' }}
@@ -157,6 +148,7 @@ jobs:
           GPG_KEY: ${{ secrets.GPG_KEY }}
         run: |
           if [ -z "${GPG_KEY}" ] || [ "${GPG_KEY}" = "" ]; then
+            echo "GPG_KEY is not set. Please see the output of the 'Report missing repository secrets/variables' job below."
             exit 1
           else
             echo "GPG_KEY is set."
@@ -170,6 +162,7 @@ jobs:
           GPG_KEYID: ${{ secrets.GPG_KEYID }}
         run: |
           if [ -z "${GPG_KEYID}" ] || [ "${GPG_KEYID}" = "" ]; then
+            echo "GPG_KEYID is not set. Please see the output of the 'Report missing repository secrets/variables' job below."
             exit 1
           else
             echo "GPG_KEYID is set."
@@ -183,13 +176,28 @@ jobs:
           GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
         run: |
           if [ -z "${GPG_PASSPHRASE}" ] || [ "${GPG_PASSPHRASE}" = "" ]; then
+            echo "GPG_PASSPHRASE is not set. Please see the output of the 'Report missing repository secrets/variables' job below."
             exit 1
           else
             echo "GPG_PASSPHRASE is set."
           fi
         id: check-gpg-passphrase
 
-      - name: Report which secrets are missing from repository
+      - name: Check if MAVEN_SETTINGS_XML is configured in this repository
+        if: ${{ inputs.check_maven_settings_xml == 'true' }}
+        continue-on-error: true
+        env:
+          MAVEN_SETTINGS_XML: ${{ secrets.MAVEN_SETTINGS_XML }}
+        run: |
+          if [ -z "${MAVEN_SETTINGS_XML}" ] || [ "${MAVEN_SETTINGS_XML}" == "" ]; then
+            echo "MAVEN_SETTINGS_XML is not set. Please see the output of the 'Report missing repository secrets/variables' job below."
+            exit 1
+          else
+            echo "MAVEN_SETTINGS_XML is set."
+          fi
+        id: check-maven-settings-xml
+
+      - name: Report missing repository secrets/variables
         if: ${{ 
           steps.check-write-github-packages-username.outcome == 'failure' || 
           steps.check-write-github-packages-token.outcome == 'failure' || 
@@ -202,7 +210,7 @@ jobs:
           }}
         run: |
           if [[ ${{ steps.check-write-github-packages-username.outcome }} == 'failure' ]]; then
-            echo "WRITE_GITHUB_PACKAGES_USERNAME is not set. Please configure it in the repository secrets.\
+            echo "WRITE_GITHUB_PACKAGES_USERNAME is not set. Please configure it in the repository variables.\
             It must contain the GitHub username you want to use to log into GitHub Container Registry."
           fi
           if [[ ${{ steps.check-write-github-packages-token.outcome }} == 'failure' ]]; then
