download all needed artifacts
Signed-off-by: Jade Carino <carino_jade@yahoo.co.uk>

diff --git a/.github/workflows/obr.yaml b/.github/workflows/obr.yaml
--- a/.github/workflows/obr.yaml
+++ b/.github/workflows/obr.yaml
@@ -39,7 +39,6 @@ jobs:
         #   cache: 'maven'
   
       - name: Print githash
-        working-directory: obr
         run: |
           echo $GITHUB_SHA > ./obr.githash
 
@@ -86,17 +85,41 @@ jobs:
         run: |
           cat modules/obr/galasa-bom/pom.xml
 
+      - name: Download wrapping artifacts
+        uses: actions/download-artifact@v4
+        with:
+            name: wrapping
+            path: modules/wrapping/dev/galasa
+
+      - name: Download gradle artifacts
+        uses: actions/download-artifact@v4
+        with:
+            name: gradle
+            path: modules/artifacts/dev/galasa
+
+      - name: Download maven artifacts
+        uses: actions/download-artifact@v4
+        with:
+            name: maven
+            path: modules/artifacts/dev/galasa
+
+      - name: Download framework artifacts
+        uses: actions/download-artifact@v4
+        with:
+            name: framework
+            path: modules/artifacts/dev/galasa
+
       - name: Download extensions artifacts
         uses: actions/download-artifact@v4
         with:
           name: extensions
-          path: modules/artifacts
+          path: modules/artifacts/dev/galasa
 
       - name: Download managers artifacts
         uses: actions/download-artifact@v4
         with:
             name: managers
-            path: modules/artifacts
+            path: modules/artifacts/dev/galasa
         
       - name: Build Galasa BOM with maven
         working-directory: modules/obr
@@ -121,7 +144,7 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
             name: obr
-            path: modules/obr/artifacts
+            path: modules/obr/artifacts/dev/galasa
             retention-days: 7
       
       - name:  Generate Galasa OBR
@@ -246,14 +269,51 @@ jobs:
       - name: Display Galasa Javadoc pom.xml 
         run: |
           cat modules/obr/javadocs/pom.xml
+
+      - name: Download wrapping artifacts
+        uses: actions/download-artifact@v4
+        with:
+            name: wrapping
+            path: modules/wrapping/dev/galasa
+  
+      - name: Download gradle artifacts
+        uses: actions/download-artifact@v4
+        with:
+            name: gradle
+            path: modules/artifacts/dev/galasa
+  
+      - name: Download maven artifacts
+        uses: actions/download-artifact@v4
+        with:
+            name: maven
+            path: modules/artifacts/dev/galasa
+  
+      - name: Download framework artifacts
+        uses: actions/download-artifact@v4
+        with:
+            name: framework
+            path: modules/artifacts/dev/galasa
+  
+      - name: Download extensions artifacts
+        uses: actions/download-artifact@v4
+        with:
+            name: extensions
+            path: modules/artifacts/dev/galasa
+  
+      - name: Download managers artifacts
+        uses: actions/download-artifact@v4
+        with:
+            name: managers
+            path: modules/artifacts/dev/galasa
         
       - name: Build javadoc site using maven
         working-directory: modules/obr
         run: |
           set -o pipefail
           mvn -f javadocs/pom.xml deploy -X \
+          -Dgalasa.source.repo=file:${{ github.workspace }}/modules/artifacts \
           -Dgalasa.central.repo=https://repo.maven.apache.org/maven2/ \
-          -Dgalasa.release.repo=file:${{ github.workspace }}/obr/javadocs/docker/repo \
+          -Dgalasa.release.repo=file:${{ github.workspace }}/modules/obr/javadocs/docker/repo \
           -Dmaven.javadoc.failOnError=false \
           --batch-mode --errors --fail-at-end \
           --settings /home/runner/work/gpg/settings.xml 2>&1 | tee build.log
@@ -324,149 +384,149 @@ jobs:
     #     run: |
     #       docker run --env ARGOCD_AUTH_TOKEN=${{ env.ARGOCD_AUTH_TOKEN }} --rm -v ${{ github.workspace }}:/var/workspace ghcr.io/galasa-dev/argocdcli:main app wait ${{ env.BRANCH }}-maven-repos --resource apps:Deployment:javadoc-${{ env.BRANCH }} --health --server argocd.galasa.dev
 
-  build-obr-generic:
-    name: Build OBR embedded and boot images using galasabld and maven
-    runs-on: ubuntu-latest
-    needs: [build-obr, build-obr-javadocs]
+#   build-obr-generic:
+#     name: Build OBR embedded and boot images using galasabld and maven
+#     runs-on: ubuntu-latest
+#     needs: [build-obr, build-obr-javadocs]
 
-    steps:
-      - name: Checkout Code
-        uses: actions/checkout@v4
+#     steps:
+#       - name: Checkout Code
+#         uses: actions/checkout@v4
 
-      - name: Set up JDK
-        uses: actions/setup-java@v4
-        with:
-          java-version: '17'
-          distribution: 'semeru'
-        #   cache: 'maven'
+#       - name: Set up JDK
+#         uses: actions/setup-java@v4
+#         with:
+#           java-version: '17'
+#           distribution: 'semeru'
+#         #   cache: 'maven'
 
-      - name: Make secrets directory
-        run : |
-            mkdir /home/runner/work/secrets
+#       - name: Make secrets directory
+#         run : |
+#             mkdir /home/runner/work/secrets
 
-      - name: Copy settings.xml
-        env:
-            MAVEN_SETTINGS_XML: ${{ secrets.MAVEN_SETTINGS_XML }}
-        run : |
-            echo $MAVEN_SETTINGS_XML > /home/runner/work/secrets/settings.xml
+#       - name: Copy settings.xml
+#         env:
+#             MAVEN_SETTINGS_XML: ${{ secrets.MAVEN_SETTINGS_XML }}
+#         run : |
+#             echo $MAVEN_SETTINGS_XML > /home/runner/work/secrets/settings.xml
       
-      - name: Copy GPG passphrase
-        env:
-            GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
-        run : |
-            echo $GPG_PASSPHRASE > /home/runner/work/secrets/passphrase.file
+#       - name: Copy GPG passphrase
+#         env:
+#             GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
+#         run : |
+#             echo $GPG_PASSPHRASE > /home/runner/work/secrets/passphrase.file
       
-      - name: Copy GPG key
-        env:
-            GPG_KEY_BASE64: ${{ secrets.GPG_KEY }}
-        run : |
-            echo $GPG_KEY_BASE64 |  base64 --decode > /home/runner/work/secrets/galasa.gpg
+#       - name: Copy GPG key
+#         env:
+#             GPG_KEY_BASE64: ${{ secrets.GPG_KEY }}
+#         run : |
+#             echo $GPG_KEY_BASE64 |  base64 --decode > /home/runner/work/secrets/galasa.gpg
             
-      - name: Make GPG home directory and change permissions
-        run: |
-            mkdir /home/runner/work/gpg
-            chmod '700' /home/runner/work/gpg
+#       - name: Make GPG home directory and change permissions
+#         run: |
+#             mkdir /home/runner/work/gpg
+#             chmod '700' /home/runner/work/gpg
         
-      - name: Import GPG
-        run: |
-            gpg --homedir /home/runner/work/gpg --pinentry-mode loopback --passphrase-file /home/runner/work/secrets/passphrase.file --import /home/runner/work/secrets/galasa.gpg
+#       - name: Import GPG
+#         run: |
+#             gpg --homedir /home/runner/work/gpg --pinentry-mode loopback --passphrase-file /home/runner/work/secrets/passphrase.file --import /home/runner/work/secrets/galasa.gpg
         
-      - name: Copy custom settings.xml
-        run: |
-            cp /home/runner/work/secrets/settings.xml /home/runner/work/gpg/settings.xml
+#       - name: Copy custom settings.xml
+#         run: |
+#             cp /home/runner/work/secrets/settings.xml /home/runner/work/gpg/settings.xml
       
-      - name:  Generate Galasa OBR generic pom.xml
-        run: |
-          docker run --rm -v ${{ github.workspace }}/modules:/var/root/ ghcr.io/galasa-dev/galasabld-amd64:main template --releaseMetadata var/root/framework/release.yaml --releaseMetadata /var/root/extensions/release.yaml --releaseMetadata /var/root/managers/release.yaml --releaseMetadata /var/root/obr/release.yaml --template /var/root/obr/obr-generic/pom.template --output /var/root/obr/obr-generic/pom.xml --obr
+#       - name:  Generate Galasa OBR generic pom.xml
+#         run: |
+#           docker run --rm -v ${{ github.workspace }}/modules:/var/root/ ghcr.io/galasa-dev/galasabld-amd64:main template --releaseMetadata var/root/framework/release.yaml --releaseMetadata /var/root/extensions/release.yaml --releaseMetadata /var/root/managers/release.yaml --releaseMetadata /var/root/obr/release.yaml --template /var/root/obr/obr-generic/pom.template --output /var/root/obr/obr-generic/pom.xml --obr
            
-      - name: Display Galasa OBR generic pom.xml
-        run: |
-          cat modules/obr/obr-generic/pom.xml
+#       - name: Display Galasa OBR generic pom.xml
+#         run: |
+#           cat modules/obr/obr-generic/pom.xml
         
-      - name: Build Galasa OBR generic pom.xml with maven
-        working-directory: modules/obr/obr-generic
-        run: |
-          set -o pipefail
-          mvn -f pom.xml process-sources -X \
-          -Dgalasa.central.repo=https://repo.maven.apache.org/maven2/ \
-          dev.galasa:galasa-maven-plugin:0.15.0:obrembedded \
-          --batch-mode --errors --fail-at-end \
-          --settings /home/runner/work/gpg/settings.xml 2>&1 | tee build.log
+#       - name: Build Galasa OBR generic pom.xml with maven
+#         working-directory: modules/obr/obr-generic
+#         run: |
+#           set -o pipefail
+#           mvn -f pom.xml process-sources -X \
+#           -Dgalasa.central.repo=https://repo.maven.apache.org/maven2/ \
+#           dev.galasa:galasa-maven-plugin:0.15.0:obrembedded \
+#           --batch-mode --errors --fail-at-end \
+#           --settings /home/runner/work/gpg/settings.xml 2>&1 | tee build.log
         
-      - name: Upload galasa obr generic Build Log
-        if: failure()
-        uses: actions/upload-artifact@v4
-        with:
-          name: galasa-obr-generic-build-log
-          path: modules/obr/obr-generic/build.log
-          retention-days: 7
+#       - name: Upload galasa obr generic Build Log
+#         if: failure()
+#         uses: actions/upload-artifact@v4
+#         with:
+#           name: galasa-obr-generic-build-log
+#           path: modules/obr/obr-generic/build.log
+#           retention-days: 7
 
-      - name: Login to Github Container Registry
-        uses: docker/login-action@v3
-        with:
-          registry: ${{ env.REGISTRY }}
-          username: galasa-team
-          password: ${{ secrets.GALASA_TEAM_WRITE_PACKAGES_TOKEN }}
+#       - name: Login to Github Container Registry
+#         uses: docker/login-action@v3
+#         with:
+#           registry: ${{ env.REGISTRY }}
+#           username: galasa-team
+#           password: ${{ secrets.GALASA_TEAM_WRITE_PACKAGES_TOKEN }}
     
-      - name: Extract metadata for OBR generic image
-        id: metadata-obr-generic
-        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
-        with:
-          images: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/obr-generic
+#       - name: Extract metadata for OBR generic image
+#         id: metadata-obr-generic
+#         uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
+#         with:
+#           images: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/obr-generic
   
-      - name: Build and push obr-generic
-        id: build-obr-generic
-        uses: docker/build-push-action@v5
-        with:
-          context: obr
-          file: obr/dockerfiles/dockerfile.obrgeneric
-          push: false
-          tags: ${{ steps.metadata-obr-generic.outputs.tags }}
-          labels: ${{ steps.metadata-obr-generic.outputs.labels }}
+#       - name: Build and push obr-generic
+#         id: build-obr-generic
+#         uses: docker/build-push-action@v5
+#         with:
+#           context: obr
+#           file: obr/dockerfiles/dockerfile.obrgeneric
+#           push: false
+#           tags: ${{ steps.metadata-obr-generic.outputs.tags }}
+#           labels: ${{ steps.metadata-obr-generic.outputs.labels }}
 
-      - name: Copy files from kubectl image for Galasa boot embedded images
-        run: |
-          mkdir -p /opt/k8s/bin
-          curl -L https://dl.k8s.io/release/v1.22.0/bin/linux/amd64/kubectl -o /opt/k8s/bin/kubectl
-          chmod +x /opt/k8s/bin/kubectl
-          cp -vr /opt/k8s/bin/kubectl ${{ github.workspace }}/obr/dockerfiles/trace-log4j.properties ${{ github.workspace }}/obr/obr-generic/
+#       - name: Copy files from kubectl image for Galasa boot embedded images
+#         run: |
+#           mkdir -p /opt/k8s/bin
+#           curl -L https://dl.k8s.io/release/v1.22.0/bin/linux/amd64/kubectl -o /opt/k8s/bin/kubectl
+#           chmod +x /opt/k8s/bin/kubectl
+#           cp -vr /opt/k8s/bin/kubectl ${{ github.workspace }}/obr/dockerfiles/trace-log4j.properties ${{ github.workspace }}/obr/obr-generic/
 
-      - name: Extract metadata for Galasa boot embedded image
-        id: metadata-boot-embedded
-        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
-        with:
-          images: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/galasa-boot-embedded-x86_64
+#       - name: Extract metadata for Galasa boot embedded image
+#         id: metadata-boot-embedded
+#         uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
+#         with:
+#           images: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/galasa-boot-embedded-x86_64
   
-      - name: Build and push Galasa boot embedded image
-        id: build-boot-embedded
-        uses: docker/build-push-action@v5
-        with:
-          context: obr
-          file: obr/dockerfiles/dockerfile.bootembedded
-          push: false
-          tags: ${{ steps.metadata-boot-embedded.outputs.tags }}
-          labels: ${{ steps.metadata-boot-embedded.outputs.labels }}
-          build-args: |
-            tag=${{ env.BRANCH }}
-            dockerRepository=${{ env.REGISTRY }}
-            jdkImage=harbor.galasa.dev/docker_proxy_cache/library/openjdk:17
+#       - name: Build and push Galasa boot embedded image
+#         id: build-boot-embedded
+#         uses: docker/build-push-action@v5
+#         with:
+#           context: obr
+#           file: obr/dockerfiles/dockerfile.bootembedded
+#           push: false
+#           tags: ${{ steps.metadata-boot-embedded.outputs.tags }}
+#           labels: ${{ steps.metadata-boot-embedded.outputs.labels }}
+#           build-args: |
+#             tag=${{ env.BRANCH }}
+#             dockerRepository=${{ env.REGISTRY }}
+#             jdkImage=harbor.galasa.dev/docker_proxy_cache/library/openjdk:17
 
-      - name: Extract metadata for Galasa IBM boot embedded image
-        id: metadata-ibm-boot-embedded
-        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
-        with:
-          images: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/galasa-ibm-boot-embedded-x86_64
+#       - name: Extract metadata for Galasa IBM boot embedded image
+#         id: metadata-ibm-boot-embedded
+#         uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
+#         with:
+#           images: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/galasa-ibm-boot-embedded-x86_64
   
-      - name: Build and push Galasa IBM boot embedded image
-        id: build-ibm-boot-embedded
-        uses: docker/build-push-action@v5
-        with:
-          context: obr
-          file: obr/dockerfiles/dockerfile.ibmbootembedded
-          push: false
-          tags: ${{ steps.metadata-ibm-boot-embedded.outputs.tags }}
-          labels: ${{ steps.metadata-ibm-boot-embedded.outputs.labels }}
-          build-args: |
-            tag=${{ env.BRANCH }}
-            dockerRepository=${{ env.REGISTRY }}
-            platform=x86_64
+#       - name: Build and push Galasa IBM boot embedded image
+#         id: build-ibm-boot-embedded
+#         uses: docker/build-push-action@v5
+#         with:
+#           context: obr
+#           file: obr/dockerfiles/dockerfile.ibmbootembedded
+#           push: false
+#           tags: ${{ steps.metadata-ibm-boot-embedded.outputs.tags }}
+#           labels: ${{ steps.metadata-ibm-boot-embedded.outputs.labels }}
+#           build-args: |
+#             tag=${{ env.BRANCH }}
+#             dockerRepository=${{ env.REGISTRY }}
+#             platform=x86_64
